import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import DefaultProvider from '@/components/shared/providers/DefaultProvider';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-white container mx-auto py-24`}>
        <DefaultProvider>
          <Suspense fallback='Loading...'>{children}</Suspense>
        </DefaultProvider>
      </body>
    </html>
  );
}
